-- in lua/core/plugin_config/init.lua
require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.toggleterm")
require("core.plugin_config.autopairs")
require("core.plugin_config.surround")
require("core.plugin_config.rust")
require("core.plugin_config.godot")
require("core.plugin_config.react_python")
require("core.plugin_config.dap_config")
